# Generated by Django 5.1.15 on 2026-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_for_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Change amount for cash payments', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(blank=True, help_text='Structured address for delivery orders', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Dinheiro'), ('CARD_ON_DELIVERY', 'Cartão na entrega'), ('PIX', 'PIX')], default='', max_length=20),
        ),
    ]
