# Generated by Django 5.1.15 on 2026-03-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_customer_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('OWN', 'Canal próprio'), ('IFOOD', 'iFood'), ('99FOOD', '99Food'), ('RAPPI', 'Rappi'), ('OTHER', 'Outro')], default='OWN', max_length=20),
        ),
    ]
