# Generated by Django 5.1.15 on 2026-03-02 22:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cdp', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SCHEDULED', 'Agendada'), ('RUNNING', 'Rodando'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=15)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Quando disparar (null = manual)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, help_text='Null = campanha de rede (todas as stores)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('opted_out_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SCHEDULED', 'Agendada'), ('RUNNING', 'Rodando'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='RUNNING', max_length=15)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='crm.campaign')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=20)),
                ('subject', models.CharField(blank=True, default='', help_text='Assunto (email)', max_length=255)),
                ('body', models.TextField(help_text='Corpo com variáveis {{name}}, {{store_name}}, {{coupon_code}}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='crm.campaigntemplate'),
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('criteria', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='crm.customersegment'),
        ),
        migrations.CreateModel(
            name='TenantBillingQuota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_contacts', models.PositiveIntegerField(default=1000, help_text='Teto do plano atual')),
                ('current_period_contacts', models.PositiveIntegerField(default=0, help_text='Contatos usados no período atual')),
                ('period_start', models.DateField(default=django.utils.timezone.now)),
                ('alert_sent_at_80', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_quota', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('DELIVERED', 'Entregue'), ('FAILED', 'Falhou'), ('OPTED_OUT', 'Sem consentimento')], default='PENDING', max_length=15)),
                ('channel', models.CharField(max_length=20)),
                ('destination', models.CharField(blank=True, default='', help_text='Telefone/email destino', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='cdp.customer')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='crm.campaignrun')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('run', 'customer')},
            },
        ),
    ]
