# Generated by Django 5.1.15 on 2026-03-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oauthstate',
            new_name='oauth_oauth_state_4bb388_idx',
            old_name='oauth_oauthst_state_idx',
        ),
        migrations.RenameIndex(
            model_name='oauthstate',
            new_name='oauth_oauth_provide_2e820e_idx',
            old_name='oauth_oauthst_prov_store_idx',
        ),
    ]
