# Generated by Django 5.1.15 on 2026-03-07 12:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappiStoreCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rappi_store_id', models.CharField(help_text='Store ID on Rappi platform', max_length=128)),
                ('rappi_token', models.TextField(help_text='Bearer token provided by Rappi')),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Secret for webhook validation', max_length=255)),
                ('environment', models.CharField(choices=[('prod', 'Producao'), ('dev', 'Desenvolvimento')], default='prod', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rappi_credential', to='tenants.store')),
            ],
            options={
                'verbose_name': 'Rappi Store Credential',
            },
        ),
    ]
