# Generated by Django 5.1.15 on 2026-03-02 21:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('rfv_recency_days', models.PositiveIntegerField(blank=True, help_text='Dias desde último pedido', null=True)),
                ('rfv_frequency', models.PositiveIntegerField(default=0, help_text='Total de pedidos entregues')),
                ('rfv_monetary_cents', models.PositiveIntegerField(default=0, help_text='Valor total gasto em centavos')),
                ('rfv_last_order_at', models.DateTimeField(blank=True, null=True)),
                ('rfv_calculated_at', models.DateTimeField(blank=True, help_text='Última vez que RFV foi calculado', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Cliente sem identidade confirmada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('PUSH', 'Push notification')], max_length=20)),
                ('status', models.CharField(choices=[('GRANTED', 'Consentiu'), ('REVOKED', 'Revogou')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', help_text='Onde foi coletado', max_length=64)),
                ('legal_basis', models.CharField(blank=True, default='', help_text='Base legal LGPD', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='cdp.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ORDER_PLACED', 'Pedido realizado'), ('ORDER_DELIVERED', 'Pedido entregue'), ('ORDER_CANCELLED', 'Pedido cancelado'), ('COUPON_USED', 'Cupom utilizado'), ('CONSENT_GRANTED', 'Consentimento concedido'), ('CONSENT_REVOKED', 'Consentimento revogado'), ('PROFILE_UPDATED', 'Perfil atualizado')], max_length=30)),
                ('payload', models.JSONField(default=dict, help_text='Dados do evento (order_id, coupon_code, etc.)')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cdp.customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_events', to='tenants.store')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PHONE', 'Telefone'), ('EMAIL', 'E-mail'), ('CPF', 'CPF'), ('IFOOD_ID', 'iFood ID'), ('99FOOD_ID', '99Food ID'), ('EXTERNAL', 'Externo')], max_length=20)),
                ('value', models.CharField(help_text='Valor da identidade (ex: +5511999999999)', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', help_text='Origem (ifood, own, manual)', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='cdp.customer')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'phone'], name='cdp_custome_tenant__b9600d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'email'], name='cdp_custome_tenant__7c25b9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'rfv_recency_days'], name='cdp_custome_tenant__6ed37e_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['customer', 'channel', '-created_at'], name='cdp_consent_custome_02a007_idx'),
        ),
        migrations.AddIndex(
            model_name='customerevent',
            index=models.Index(fields=['customer', 'event_type'], name='cdp_custome_custome_500998_idx'),
        ),
        migrations.AddIndex(
            model_name='customerevent',
            index=models.Index(fields=['customer', 'occurred_at'], name='cdp_custome_custome_aa7104_idx'),
        ),
        migrations.AddIndex(
            model_name='customeridentity',
            index=models.Index(fields=['type', 'value'], name='cdp_custome_type_bdb8e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customeridentity',
            unique_together={('customer', 'type', 'value')},
        ),
    ]
