# Generated by Django 5.1.15 on 2026-03-02 21:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('min_choices', models.PositiveSmallIntegerField(default=0, help_text='Mínimo obrigatório (0 = opcional)')),
                ('max_choices', models.PositiveSmallIntegerField(default=1, help_text='Máximo permitido')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('DRAFT', 'Rascunho')], default='DRAFT', max_length=10)),
                ('channels', models.JSONField(default=list, help_text='Canais onde este catálogo é exibido. Vazio = todos.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='tenants.company')),
                ('store', models.ForeignKey(blank=True, help_text='Se null, catálogo é compartilhado para todas as stores da company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='tenants.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('DRAFT', 'Rascunho')], default='ACTIVE', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.catalog')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_delta_cents', models.IntegerField(default=0, help_text='Acréscimo (+) ou desconto (-) em centavos')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.modifiergroup')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('price_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('DRAFT', 'Rascunho')], default='ACTIVE', max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('serving_size', models.CharField(blank=True, default='', max_length=50)),
                ('calories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='catalog.product'),
        ),
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_day', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='catalog.product')),
            ],
            options={
                'ordering': ['week_day', 'start_time'],
                'unique_together': {('product', 'week_day', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='ProductChannelMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('OWN', 'Canal próprio'), ('IFOOD', 'iFood'), ('99FOOD', '99Food'), ('ALL', 'Todos os canais')], max_length=20)),
                ('external_id', models.CharField(help_text='ID do produto no canal externo', max_length=255)),
                ('external_sku', models.CharField(blank=True, default='', max_length=255)),
                ('price_override_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_maps', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', 'external_id'], name='catalog_pro_channel_6398dc_idx')],
                'unique_together': {('product', 'channel')},
            },
        ),
    ]
