# Generated by Django 5.1.15 on 2026-03-03 00:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('default_kds_stations', models.JSONField(default=list, help_text='[{"name": "Chapa", "category": "GRILL", "display_order": 1}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_template', to='tenants.company')),
                ('template_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchise_templates', to='catalog.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('STOCK_CRITICAL', 'Estoque crítico'), ('RFV_DROP', 'Queda de frequência'), ('KDS_BACKLOG', 'Fila KDS acumulada')], max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Dados do alerta')),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_alerts', to='tenants.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_alerts', to='tenants.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_price_overrides', models.JSONField(default=dict, help_text='{"<product_uuid>": 3200}')),
                ('product_status_overrides', models.JSONField(default=dict, help_text='{"<product_uuid>": "INACTIVE"}')),
                ('bom_overrides', models.JSONField(default=dict, help_text='{"<bom_uuid>": "0.150"}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_override', to='tenants.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_overrides', to='enterprise.franchisetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseeOnboarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Executando'), ('DONE', 'Concluído'), ('FAILED', 'Falhou')], default='PENDING', max_length=10)),
                ('steps_completed', models.JSONField(default=list, help_text='["copy_catalog", "copy_kds_stations", "copy_bom", "create_billing_quota", "create_store_override"]')),
                ('error_detail', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='tenants.store')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboardings', to='enterprise.franchisetemplate')),
            ],
            options={
                'unique_together': {('template', 'store')},
            },
        ),
        migrations.CreateModel(
            name='NetworkReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('DAILY', 'Diário'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensal')], max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('data', models.JSONField(default=dict, help_text='Métricas consolidadas por store: orders, revenue, rfv, stock_alerts')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_reports', to='tenants.company')),
            ],
            options={
                'ordering': ['-date_from'],
                'unique_together': {('company', 'period', 'date_from')},
            },
        ),
    ]
