# Generated by Django 5.1.15 on 2026-03-02 22:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=[('kg', 'Quilograma'), ('g', 'Grama'), ('L', 'Litro'), ('mL', 'Mililitro'), ('un', 'Unidade'), ('cx', 'Caixa'), ('pct', 'Pacote')], default='un', max_length=5)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, help_text='Quantidade mínima para alerta', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='tenants.store')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('minimum_qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='tenants.store')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stock.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('is_below_minimum', models.BooleanField(default=False)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='stock.stockitem')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, help_text='Quantidade consumida por unidade do produto', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='catalog.product')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='stock.stockitem')),
            ],
            options={
                'unique_together': {('product', 'stock_item')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('PERDA', 'Perda/Desperdício'), ('INVENTARIO', 'Inventário')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positivo=entrada, Negativo=saída', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50)),
                ('reference_id', models.CharField(blank=True, default='', max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stockitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='tenants.store')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['stock_item', 'occurred_at'], name='stock_stock_stock_i_a0d4a4_idx'), models.Index(fields=['store', 'type'], name='stock_stock_store_i_ca5b54_idx'), models.Index(fields=['reference_type', 'reference_id'], name='stock_stock_referen_928410_idx')],
            },
        ),
    ]
