# Generated by Django 5.1.15 on 2026-03-02 21:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDSStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GRILL', 'Chapa/Grill'), ('COLD', 'Frio/Saladas'), ('DRINKS', 'Bebidas'), ('DESSERTS', 'Sobremesas'), ('GENERAL', 'Geral'), ('PACKING', 'Embalagem/Expedição')], default='GENERAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Display order in the panel')),
                ('filter_order_types', models.JSONField(blank=True, default=list, help_text='List of order_type this station displays. Empty = all.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_stations', to='tenants.store')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KDSTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WAITING', 'Aguardando'), ('IN_PROGRESS', 'Em preparo'), ('DONE', 'Concluído')], default='WAITING', max_length=20)),
                ('enqueued_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When it entered the station queue')),
                ('started_at', models.DateTimeField(blank=True, help_text='When operator started prep', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When operator marked done', null=True)),
                ('wait_time_seconds', models.PositiveIntegerField(blank=True, help_text='Wait time until prep started', null=True)),
                ('prep_time_seconds', models.PositiveIntegerField(blank=True, help_text='Prep time (started -> completed)', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_tickets', to='orders.order')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='kds.kdsstation')),
            ],
            options={
                'ordering': ['enqueued_at'],
                'indexes': [models.Index(fields=['station', 'status'], name='kds_kdstick_station_673166_idx'), models.Index(fields=['station', 'enqueued_at'], name='kds_kdstick_station_2170ba_idx')],
                'unique_together': {('station', 'order')},
            },
        ),
    ]
