# Generated by Django 5.1.15 on 2026-03-02 21:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFoodStoreCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(help_text='iFood merchantId', max_length=128)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(help_text='Store encrypted in production', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Secret for X-IFood-Signature', max_length=255)),
                ('access_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ifood_credential', to='tenants.store')),
            ],
            options={
                'verbose_name': 'iFood Store Credential',
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='ifood', max_length=32)),
                ('event_id', models.CharField(help_text='Event ID in the source system', max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=64)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('store_id', models.UUIDField(blank=True, null=True)),
                ('payload', models.JSONField(help_text='Raw payload, immutable')),
                ('headers', models.JSONField(default=dict, help_text='Relevant headers (no auth)')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('ENQUEUED', 'Enfileirado'), ('PROCESSING', 'Processando'), ('PROCESSED', 'Processado'), ('DUPLICATE', 'Duplicado'), ('FAILED', 'Falhou')], default='RECEIVED', max_length=20)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['source', 'event_id'], name='ifood_rawev_source_7b7e26_idx'), models.Index(fields=['status', 'received_at'], name='ifood_rawev_status_4875c0_idx'), models.Index(fields=['tenant_id', 'store_id'], name='ifood_rawev_tenant__5ff846_idx')],
            },
        ),
    ]
