# Generated by Django 5.1.15 on 2026-03-03 19:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinetyNineStoreCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(help_text='merchantId 99Food', max_length=128)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(help_text='Store encrypted in production', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Secret for X-Ninetynine-Signature', max_length=255)),
                ('access_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ninetynine_credential', to='tenants.store')),
            ],
            options={
                'verbose_name': '99Food Store Credential',
            },
        ),
    ]
